services:

  drupal:
    image: drupal:11
    container_name: drupal_app
    ports:
      - "8080:80"
    volumes:
      - ./web:/opt/drupal/web
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: drupal_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

volumes:
  mysql_data: